name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.9.0
      QT_DIR: C:\Qt\6.9.0\mingw_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install aqt
        run: python -m pip install --upgrade aqtinstall

      - name: Install Qt
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} win64_mingw --outputdir C:\Qt --modules qtbase qtsvg --base https://mirrors.tuna.tsinghua.edu.cn/qt/

      - name: Add MSYS2 to PATH
        uses: msys2/setup-msys2@v2
        with:
          update: false
          install: mingw-w64-x86_64-toolchain

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}"

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run windeployqt
        run: |
          $qtBin = "${{ env.QT_DIR }}\bin"
          & "$qtBin\windeployqt6.exe" --compiler-runtime --release --dir build\bin build\bin\FileManager.exe

      - name: Archive bin directory
        run: |
          Compress-Archive -Path build\bin\* -DestinationPath FileManager-win.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileManager-win
          path: FileManager-win.zip
