name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.9.0
      QT_DIR: C:\Qt\6.9.0\mingw_64
      QT_MIRROR: https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_690/qt6_690/qt.qt6.690.win64_mingw

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Qt
        run: |
          curl -L -o qtbase.7z ${{ env.QT_MIRROR }}/6.9.0-0-202503301022qtbase-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z
          curl -L -o qttools.7z ${{ env.QT_MIRROR }}//6.9.0-0-202503301022qttools-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z
          curl -L -o qtsvg.7z ${{ env.QT_MIRROR }}//6.9.0-0-202503301022qtsvg-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z
          curl -L -o extra.7z ${{ env.QT_MIRROR }}//6.9.0-0-202503301022MinGW-w64-x86_64-13.1.0-release-posix-seh-msvcrt-rt_v11-rev1-runtime.7z
     
      - name: Extract files
        run: |
          7z x qtbase.7z -o${{ env.QT_DIR }}
          7z x qttools.7z -o${{ env.QT_DIR }}
          7z x qtsvg.7z -o${{ env.QT_DIR }}
          7z x extra.7z -o${{ env.QT_DIR }}\bin

      - name: Add MSYS2 to PATH
        uses: msys2/setup-msys2@v2
        with:
          update: false
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${QT_DIR}"

      - name: Build
        shell: msys2 {0}
        run: |
          cmake --build build --config Release --target all -j 14

      - name: Run windeployqt
        shell: cmd
        run: |
          "${{ env.QT_DIR }}\bin\windeployqt6.exe" --compiler-runtime --release --dir build\bin build\bin\FileManager.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileManager-win
          path: build\bin
