name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.9.0
      QT_DIR: C:\Qt\6.9.0\mingw_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download QtBase
        run: |
          curl -L -o qtbase.7z https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_690/qt6_690/qt.qt6.690.win64_mingw/6.9.0-0-202503301022qtbase-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z

      - name: Download QtTools
        run: |
          curl -L -o qttools.7z https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_690/qt6_690/qt.qt6.690.win64_mingw/6.9.0-0-202503301022qttools-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z

      - name: Download QtSvg
        run: |
          curl -L -o qtsvg.7z https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_690/qt6_690/qt.qt6.690.win64_mingw/6.9.0-0-202503301022qtsvg-Windows-Windows_10_22H2-Mingw-Windows-Windows_10_22H2-X86_64.7z
      
      - name: Download Extra
        run: |
          curl -L -o extra.7z https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_690/qt6_690/qt.qt6.690.win64_mingw/6.9.0-0-202503301022MinGW-w64-x86_64-13.1.0-release-posix-seh-msvcrt-rt_v11-rev1-runtime.7z

      - name: Extract QtBase
        run: |
          7z x qtbase.7z -oC:\Qt\6.9.0\mingw_64

      - name: Extract QtTools
        run: |
          7z x qttools.7z -oC:\Qt\6.9.0\mingw_64

      - name: Extract QtSvg
        run: |
          7z x qtsvg.7z -oC:\Qt\6.9.0\mingw_64

      - name: Extract Extra
        run: |
          7z x extra.7z -oC:\Qt\6.9.0\mingw_64

      - name: Add MSYS2 to PATH
        uses: msys2/setup-msys2@v2
        with:
          update: false
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake

      - name: Configure CMake
        run: |
          C:\msys64\mingw64\bin\cmake.exe -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}"

      - name: Build
        run: |
          C:\msys64\mingw64\bin\cmake.exe --build build --config Release --target all -j 14

      - name: Run windeployqt
        run: |
          $qtBin = "${{ env.QT_DIR }}\bin"
          & "$qtBin\windeployqt6.exe" --compiler-runtime --release --dir build\bin build\bin\FileManager.exe

      - name: Archive bin directory
        run: |
          Compress-Archive -Path build\bin\* -DestinationPath FileManager-win.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileManager-win
          path: FileManager-win.zip
